# Generated by Django 5.1.4 on 2025-02-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='6A6E7B5CE7B24C06862C901EC49644B9', editable=False, max_length=32, unique=True),
        ),
    ]
