# Generated by Django 5.1.4 on 2025-02-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='F906B9A701CD42A59B2B781934CD3A0A', editable=False, max_length=32, unique=True),
        ),
    ]
