# Generated by Django 5.1.4 on 2025-02-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='2FA541A12BA74F11A76C24FE3DF1CEB7', editable=False, max_length=32, unique=True),
        ),
    ]
