# Generated by Django 5.1.4 on 2025-02-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='864ADCE1174B410094321C14C3DC7097', editable=False, max_length=32, unique=True),
        ),
    ]
