# Generated by Django 5.1.4 on 2025-02-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='E025C8C3B842422693198B7465F9A020', editable=False, max_length=32, unique=True),
        ),
    ]
