# Generated by Django 5.1.4 on 2025-02-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='0905219F4E5C4381993A81CD8C0CF85A', editable=False, max_length=32, unique=True),
        ),
    ]
