# Generated by Django 5.1.4 on 2025-02-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='0F3171A6804B40168F20F414226A15A7', editable=False, max_length=32, unique=True),
        ),
    ]
