# Generated by Django 5.1.4 on 2025-02-10 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_order_number'),
        ('products', '0002_remove_productfeedback_order_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeedback',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.orderitem'),
        ),
    ]
