# Generated by Django 5.1.4 on 2025-02-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productfeedback_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='S', help_text='Comma-separated sizes (e.g., S,M,L,XL)', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent_category',
            field=models.CharField(choices=[('products', 'Products')], default='products', max_length=20),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
