# Generated by Django 5.1.4 on 2025-02-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Comma-separated list of sizes (e.g., S,M,L,XL)', max_length=255, null=True),
        ),
    ]
