# Generated by Django 5.1.4 on 2025-02-15 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_alter_order_order_number'),
        ('products', '0006_alter_product_sizes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productfeedback',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_feedback'),
        ),
    ]
