# Generated by Django 5.1.4 on 2025-02-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productfeedback_unique_user_product_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent_category',
            field=models.CharField(choices=[('products', 'Products'), ('accessories', 'Accessories'), ('sale', 'Sale')], default='products', max_length=20),
        ),
    ]
