# Generated by Django 5.1.4 on 2025-02-15 22:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nav_element',
            field=models.CharField(choices=[('products', 'Products'), ('accessories', 'Accessories'), ('sale', 'Sale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
